### ISSUE TITLE
_LCDML_priority how does it work?

### ISSUE THREAD

**Issue by paulosilver** [Jomelo/LCDMenuLib#41]
hello how does _LCDML_priority work? 
How can o give priority to a backend function?
thank you

**Comment by Jomelo** [comment]
It worked like a list with an option to reset the list counter. When you use LCDML_without_priority the option to reset the list does not exists. 

The priority has no real-time effekt. 

http://jomelo.de/r/arduino/lib_simpleThread/ablauf.png

**Comment by paulosilver** [comment]
ok, so if i want to add priority to a function what do i have to do?

**Comment by Jomelo** [comment]
You do it at the initialisation with the id number 0,1,2,3 ...

**Comment by paulosilver** [comment]
<img width="908" alt="screen shot 2017-10-26 at 19 14 46" src="https://user-images.githubusercontent.com/18540022/32069754-029991e8-ba82-11e7-9425-816e74de3ac0.png">
here?

**Comment by Jomelo** [comment]
Yes, but the LCDML_BACKEND_stepper1_run and LCDML_BACKEND_stepper1_accelMov have a special return value. When the time is set to 0 and the return value has the wrong value (false), then it do not work correctly. 

In the new version of the Lib i removed the backend system because it is not a direct part of the LCDMenuLib
The new LCDMenuLib2 version can be downloaded here: https://github.com/Jomelo/LCDMenuLib2 
(all Makros and all function names have been changed)
Currently i work at the new documentation: https://github.com/Jomelo/LCDMenuLib2/wiki/Code-Reference


You can use this lib:  https://github.com/arkhipenko/TaskScheduler

**Comment by paulosilver** [comment]
ok i am going to change to that version
thank you
