### ISSUE TITLE
Difference between LCDML and LCDML2

### ISSUE THREAD

**Issue by alimnette** [Jomelo/LCDMenuLib#47]
Hello,
first of all thank you for your work.

What is the difference between LCDML and LCDML2?
my underlying question is to be able to set parameters directly from the menus with the right and left buttons :)
Thank you

**Comment by Jomelo** [comment]
Hello,

the menu structure is the same.

LCDML 2:
- remove backend system from LCDML 1
- (you can use every other task system)
- remove group system (8 groups max) from LCDML 1 
- add a condetion system (with no limit) 
- remove over 50 makros from LCDML 1 because i cannot add new functions with it 
- rewrite the complete class to use more methods insteat makros
- add an easy way to change menuitems / parameters direct in the menu

LCDML V1:
- i'm not adding new function in future ( only bug fixes )
- the group system with hidden buttons works not correctly
- the function "jumpToElement" works not correctly

**Comment by alimnette** [comment]
Hello,

OK thanks for your answer.
It is better to use the V2
